LarsLiden/NaLaPla

NaLaPla/Program.cs
Let's try this again. 
- Tree depth and subtask counts as consts
=> Parameterize depth and task count

NaLaPla/Program.cs, NaLaPla/Util.cs
To make output to terminal more readable
=> add console colors

.gitignore, NaLaPla/Program.cs, NaLaPla/Util.cs
- refactor save so can save from plan and from string version of plan (for post processing)
- saved files an put into "output" directory (in gitingore)
- post processing steps fully supported and saved to disk
- ability to load existing plan and just run post processing step
- support for flags
- input takes a flag for whether to just run post processing
- GPT3 Max tokens is a settable const
=> post process support

NaLaPla/Program.cs
- added flag for overwriting default depth
"build a house -d 4" will expand to depth 4
=> added a flag for depth

NaLaPla/.vscode/launch.json, NaLaPla/.vscode/tasks.json, NaLaPla/NaLaPla.csproj, NaLaPla/Program.cs, NaLaPla/Test.cs, NaLaPla/Util.cs
- added plan serialization load/unload
- make flags more explicit
- moved test functions to test object
=> serialization

NaLaPla/Program.cs, NaLaPla/Task.cs, NaLaPla/Test.cs, NaLaPla/Util.cs
Big merge
- Parallel requests
- Write text and JSON files 
- Load/save plans
- Display progress
=> Display progress

NaLaPla/Program.cs
Launch recursive ExpandPlans in parallel. Only tested for expand mode AS_A_LIST but should work for either.
=> Parallelize ExpandPlan

NaLaPla/OpenAIConfig.cs, NaLaPla/Program.cs
also changed calling pattern to openai to allow for multiple responses in the future
=> added openai config object

NaLaPla/Program.cs, NaLaPla/Task.cs, NaLaPla/Util.cs
- Add enums for task state
- Program.cs uses enums
- Util.cs::DisplayProgress can display enum descriptions
- Util.cs::GetDescription added to look up descriptions
=> Enums for task state

NaLaPla/Program.cs, NaLaPla/Test.cs, NaLaPla/Util.cs
Move UpdatePlan from Utils to Program
=> move update plan

NaLaPla/NaLaPla.csproj, NaLaPla/OpenAIConfig.cs, NaLaPla/Program.cs
Switch to different library that supports retrieving multiple results
=> switch openai library

NaLaPla/Plan.cs, NaLaPla/Program.cs, NaLaPla/Test.cs, NaLaPla/Util.cs
- handle multiple responses from GTP (for now defaults to always using the first)
- fixed naming problem where Plan and Task were being used interchangeably    (probably should have been a separate pull request)
=> multi-reponses

NaLaPla/Program.cs, NaLaPla/Util.cs
Still a tuple name warning I don't understand well enough to fix, and an unreachable code because of a const that should change to a variable at some point
=> Fix a bunch of warnings

NaLaPla/Program.cs, NaLaPla/RuntimeConfig.cs, NaLaPla/Test.cs, NaLaPla/Util.cs
- Create RuntimeConfig object
- Move default expansion width and depth, parallel flag, showprompts flag, and showresults flag into configuration
- Update rest of code to use config
-
=> Create runtime config object

NaLaPla/OpenAIConfig.cs, NaLaPla/Program.cs
Added voting mechanism for selecting best plan from candidates.  Not sure it's actually adding value.  Need to run more test cases to see
Disable by setting NumResponses = 1 in RuntimeConfig
=> plan voting

NaLaPla/Plan.cs, NaLaPla/Program.cs, NaLaPla/Prompt.cs, NaLaPla/RuntimeConfig.cs, NaLaPla/Util.cs
I know, I know, mixed-purpose PR. It snowballed.
- Change bool parallelGPTRequests to int maxConcurrentGPTRequests
- Create Prompt object to allow different OAIConfigs on a per-prompt basis rather than globally
=> Clean parallel + separate prompt

NaLaPla/Program.cs, NaLaPla/Prompt.cs, NaLaPla/RuntimeConfig.cs
- Add params for max concurrency, subtask word, and default temperature
- Display params at start
- Accept individual params at command line
- Use config default temp
=> Enhance params

.gitignore, NaLaPla/IR.cs, NaLaPla/NaLaPla.csproj
Rough outline for lucene index for
=> lucene outline

NaLaPla/Program.cs, NaLaPla/Prompt.cs, NaLaPla/Response.cs
- New Response object to hold individual GPT responses
- Responses have scores
- Prompts have a list of responses
- Refactor lots of stuff to use Response rather than just a string
-
=> Move responses to Response object

.gitignore, NaLaPla/IDataProvider.cs, NaLaPla/IR.cs, NaLaPla/Minecraft/MineCraftDataProvider.cs, NaLaPla/Minecraft/WikiRecord.cs, NaLaPla/Program.cs
- loading and indexing of minecraft wiki data (downloadable here: https://zenodo.org/record/6693745)
- simple search test working
=> minecraft data

NaLaPla/IR.cs, NaLaPla/Minecraft/MineCraftDataProvider.cs, NaLaPla/Minecraft/WikiRecord.cs, NaLaPla/NaLaPla.csproj, NaLaPla/Program.cs, NaLaPla/RuntimeConfig.cs, NaLaPla/Util.cs
- added support for grounding.  "useGrounding" is set to true by defauls
- add document sub-sections to search index rather than entire document
- cleaned up generate prompt code
- fix but where "-" in word splits in to multiple tasks
=> Grounding working

NaLaPla/Program.cs
- Simpler way to parameterize and add flags
- Rabid ostriches
-
=> Refactor params

.gitignore, NaLaPla/IR.cs, NaLaPla/Minecraft/MineCraftDataProvider.cs, NaLaPla/Program.cs, NaLaPla/RuntimeConfig.cs
- command line flag specifies if index should be created
- can specify directory name for data source
- moved a few things in runtimeconfig.  seems a little strange as they are actions.  may want to rethink at some point
=> index command flag

NaLaPla/Minecraft/MineCraftDataProvider.cs
Add some utility functions for creating a text only version of the MC wiki database
=> util for text only

NaLaPla/Minecraft/MineCraftDataProvider.cs, NaLaPla/Minecraft/RedditExtractor, NaLaPla/Plan.cs, NaLaPla/Program.cs, NaLaPla/Prompt.cs, NaLaPla/RuntimeConfig.cs
- minecraft wiki data indexing ignores content boxes as they just add noise
- wiki section determination using numbering to influence which sections get grouped together
- some initial rough code for reddit data extraction
- cleaned up organization of some code
=> cleanup and grounding

NaLaPla/Minecraft/MineCraftDataProvider.cs, NaLaPla/Prompt.cs
And added plan prefixing to one-by-one
=> limited table support

NaLaPla/Minecraft/MineCraftDataProvider.cs, NaLaPla/Prompt.cs, NaLaPla/RuntimeConfig.cs
Now using augmented wiki data (html tags) for better grouping of grounding data in to sections
=> use html tags for grounding sections
